"""create base tables

Revision ID: 61d99415d703
Revises: 824f3ade3a93
Create Date: 2024-04-11 08:55:07.621051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d99415d703'
down_revision: Union[str, None] = '824f3ade3a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_table_email'), 'admins_table', ['email'], unique=True)
    op.create_index(op.f('ix_admins_table_id'), 'admins_table', ['id'], unique=False)
    op.create_index(op.f('ix_admins_table_login'), 'admins_table', ['login'], unique=True)
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_table_email'), 'users_table', ['email'], unique=True)
    op.create_index(op.f('ix_users_table_id'), 'users_table', ['id'], unique=False)
    op.create_index(op.f('ix_users_table_login'), 'users_table', ['login'], unique=True)
    op.create_table('vocabularies_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabularies_table_id'), 'vocabularies_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabularies_table_id'), table_name='vocabularies_table')
    op.drop_table('vocabularies_table')
    op.drop_index(op.f('ix_users_table_login'), table_name='users_table')
    op.drop_index(op.f('ix_users_table_id'), table_name='users_table')
    op.drop_index(op.f('ix_users_table_email'), table_name='users_table')
    op.drop_table('users_table')
    op.drop_index(op.f('ix_admins_table_login'), table_name='admins_table')
    op.drop_index(op.f('ix_admins_table_id'), table_name='admins_table')
    op.drop_index(op.f('ix_admins_table_email'), table_name='admins_table')
    op.drop_table('admins_table')
    # ### end Alembic commands ###
