version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    restart: always
    volumes:
      - ./backend/src:/src
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - database
    networks:
      - easy_words

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #   restart: always
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - english_app
  #   depends_on:
  #     - backend

  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ./var/postgres:/var/lib/postgresql/data/
    networks:
      - easy_words

  redis:
    image: redis:alpine
    command: --requirepass redispass
    ports:
      - "6379:6379"
    networks:
      - easy_words

volumes:
  easy_words:

networks:
  easy_words: