name: easy_english CI/CD

on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      POSTGRES_HOST: database
      DB_PORTP: 5432
    steps:
      - uses: actions/checkout@v2
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          cd backend
          poetry install

      - name: Start test database
        run: docker-compose -f docker-compose.test.yml up -d

          
      - name: Run tests
        run: |
          cd backend/src
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          alembic upgrade head
          pytest -p no:warnings tests/
      
      - name: Stop test database
        run: docker-compose -f docker-compose.test.yml down
          
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          
      - name: Run Flake8
        run: |
          cd backend
          flake8 --config ../.flake8
